[package]
name = "rock"
version = "0.1.0"
authors = ["mahdi robatipoor <mahdi.robatipoor@gmail.com>"]
edition = "2018"
description = "share file "
homepage = "https://github.com/robatipoor/rock"
keywords = ["share", "file","rock"]
license = "MIT"
repository = "https://github.com/robatipoor/rock"

[dependencies]
aes-gcm-siv = "0.9.0"
bytes = "1.0.1"
clap = "3.0.0-beta.2"
confy = "0.4.0"
dirs = "3.0.1"
flate2 = {version = "1.0.20",features = ["tokio"]}
hex = "0.4.2"
indicatif = "0.15.0"
once_cell = "1.5.2"
pnet = "0.27.2"
rand = "0.8.3"
reqwest = "0.11.0"
serde = {version = "1.0.123",features = ["derive"] }
serde_json = "1.0.62"
sha2 = "0.9.3"
tokio = {version = "1.2",features = ["full"]} 
trust-dns-resolver = "0.20.0"
