[package]
name = "rock"
version = "0.1.0"
authors = ["mahdi robatipoor <mahdi.robatipoor@gmail.com>"]
edition = "2018"
description = "share file "
homepage = "https://github.com/robatipoor/rock"
keywords = ["share", "file","rock"]
license = "MIT"
repository = "https://github.com/robatipoor/rock"

[dependencies]
aes-gcm-siv = "0.9.0"
clap = "2.33.3"
flate2 = {version = "1.0.19",features = ["tokio"]}
once_cell = "1.5.2"
pnet = "0.27.2"
rand = "0.8.2"
reqwest = "0.11.0"
sha2 = "0.9.2"
tokio = {version = "1.0.1",features = ["full"]} 
trust-dns-resolver = "0.20.0"
